sudo: required

services:
  - docker

script:
  - docker-compose -f docker-compose.build.yml up --build musl
  - file ./packet | grep 'interpreter /lib/ld-musl-x86_64.so.1'
  - docker-compose -f docker-compose.build.yml up --build libc
  - file ./packet | grep 'interpreter /lib64/ld-linux-x86-64.so.2'
