sudo: required

env:
  global:
    - GOPATH="${HOME}/gopath"
    - DIR="${GOPATH}/src/github.com/untangle"
  matrix:
    - TARGET=libc
    - TARGET=musl

services:
  - docker

before_install:
  - env
  - pwd
  - mkdir -p "$DIR"
  - mv "$TRAVIS_BUILD_DIR" "${DIR}/classd"
  - cd "${DIR}/classd"
  - pwd
  - ls

script:
  - docker-compose -f docker-compose.build.yml up --build $TARGET

notifications:
  email: false
