sudo: required

env:
  global:
    - GOPATH="$HOME/gopath"
    - DIR="$GOPATH/src/github.com/untangle" 
  matrix:
    - TARGET=libc
    - TARGET=musl

services:
  - docker

script:
  - mkdir -p "$DIR"
  - mv "$TRAVIS_BUILD_DIR" "$DIR"
  - cd "${DIR}/classd"
  - docker-compose -f docker-compose.build.yml up --build $TARGET

notifications:
  email: false
