sudo: required

env:
  global:
    - GOPATH="${HOME}/go"
    - DIR="${GOPATH}/src/github.com/untangle"
  matrix:
    - TARGET=libc TEST="grep -q GNU/Linux"
    - TARGET=musl TEST="grep -q -v GNU/Linux"

services:
  - docker

before_install:
  - mkdir -p "$DIR"
  - mv "$TRAVIS_BUILD_DIR" "${DIR}/packetd"
  - cd "${DIR}/packetd"

script:
  - docker-compose -f docker-compose.build.yml up --build $TARGET
  - echo $LD_TARGET
  - file ./packetd
  - file ./packetd | $TEST

notifications:
  email: false
